name: Django CI/CD Workflow - Vitorino E

on:
    pull_request:
        branches:
            - dev
            - main
    
    push:
        branches:
            - main
            - dev

permissions:
  contents: write
  # pull_requests: write

jobs:
    health-check-job:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: github-actions
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Cache dependency
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}
                restore-keys: |
                    ${{ runner.os }}-pip-
            - name: Setup python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.11.4'
            - name: Check Python version
              run: python3 --version
            - name: Install requirements
              run: pip install -r requirements.txt
            - name: Check Syntax
              run: pycodestyle --statistics .
            - name: Run Migrations
              run: python3 manage.py migrate
            - name: Run Test
              run: python manage.py test
    
    package-job:
        runs-on: ubuntu-latest
        needs: [health-check-job]
        if: ${{ github.event_name == 'push' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            # - name: Build & Publish Image
            #   uses: docker/build-push-action@v5
            #   env:
            #     app_name: app
            #   with:
            #     username: _json_key
            #     password: ${{ secrets.GKE_PASSWORD }}
            #     registry: gcr.io
            #     repository: ${{secrets.GKE_PROJECT}}/ci-cd-django/app
            #     tag_with_sha: true
